### ISSUE TITLE
点歌失败卡主线程

### ISSUE THREAD

**Issue by Rothes** [HeartAge/AllMusic_P#15]
**描述**
点歌失败(获取网页错误)时导致卡主线程

**日志**
https://pastebin.com/3tXy1y1R

**服务器信息**
Server: This server is running AirplanePurpur version git-AirplanePurpur-22 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5e4deb0 on HEAD)
AllMusic: v2.12.5
Plugins (42): AACAdditionPro, AllMusic*, AntiSeedCracker, AutoBroadcastLite, BungeeTabListPlus, ChanLang, CMI, CMIEInjector*, CMILib, ConsoleSpamFix, CoreProtect, DeluxeMenus, FastAsyncWorldEdit (WorldEdit), floodgate, HoloDropsX, InventoryRollbackPlus, JoinMessage, JukeBox, LockettePro, LuckPerms, mcMMO, MoneyReward, Multiverse-Core, NeverLag*, NoteBlockAPI, OpenInv, PlaceholderAPI, PlugMan, Prism, ProtocolLib, ProtocolStringReplacer, QuickShop, Residence, Slimefun, spark, Spartan, TeleportCosts, TitleManager, Vault, ViaBackwards, ViaRewind, ViaVersion

**Comment by Coloryr** [comment]
应该是服务器核心的问题
逻辑代码都不在主线程跑却能卡主线程

**Comment by Rothes** [comment]
> 应该是服务器核心的问题
> 逻辑代码都不在主线程跑却能卡主线程

是的, 但我没有在其它服务端上测试. 如果确实是服务端问题的话, 这个议题就可以关闭了

**Comment by Rothes** [comment]
正在使用 Sugarcane 核心并且暂时未遇到该问题。
